version: 2
updates:
  - package-ecosystem: cargo
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/cube_shuffle-cordova"
    schedule:
      interval: daily