= CubeShuffle

image:https://img.shields.io/github/workflow/status/philipborg/CubeShuffle/Rust%20build%20&%20test[GitHub Workflow Status]
image:https://img.shields.io/badge/status-beta-green[Status]
link:LICENSE[image:https://img.shields.io/github/license/philipborg/CubeShuffle[GitHub]]
image:https://img.shields.io/badge/platform-Linux--x64%20%7C%20macOS--x64%20%7C%20Windows--x64%20%7C%20Android%20%7C%20Web%2FWasm32-informational[Platforms]

link:https://github.com/philipborg/CubeShuffle/subscription[image:https://img.shields.io/github/watchers/philipborg/CubeShuffle?style=social[GitHub watchers]]
image:https://img.shields.io/github/stars/philipborg/CubeShuffle?style=social[GitHub Repo stars]
image:https://img.shields.io/github/followers/philipborg?style=social[GitHub followers]

:toc:

== Summary

CubeShuffle aims to improve your card game cube shuffling by offering more control over the card distribution/randomness and/or increasing shuffling speed by combining digital and manual shuffling.
It is designed to be generic for all card games with a cube format but I, the developer, primarily play Magic The Gathering (unaffiliated).

== Installation

There are currently three different ways to install CubeShuffle.
Be aware that there are currently no automatic updates operational on any platform.

.Platforms
* link:docs/installation/Desktop.adoc[Desktop GUI] (Recommended)
* link:docs/installation/Android.adoc[Android]
* link:docs/installation/CLI.adoc[Command Line Interface]

== [#Distribution shuffle]#link:docs/distribution_shuffle.adoc[Distribution shuffle]#

A quick and easy shuffling method for cubes where cards can be assigned to and distributed based upon groups.
Offers good control over the predictability as it can be controlled from being completely random to evenly distributed.
Instructions on how to use it are available link:docs/distribution_shuffle.adoc[here].

== Predictability and randomness

You may be asking why anyone would want to control the randomness.
Shouldn't the draft be completely random?
If you want to, and it suits your cube, then I am not stopping you from complete randomness.
Use link:docs/distribution_shuffle.adoc[Distribution Shuffle] with 100% randomness for all piles to speed up a completely random cube shuffle significantly.

But most cubes don't actually want complete randomness.
You want to ensure that most deck archetypes are playable and run a low chance of them being ruined by chance, or worse bad shuffling.
(Though bad shuffling is significantly less likely when using CubeShuffle.)
This is why you never see sealed booster packs in MTG with just one card color as they are far from completely random but rather have controlled randomness.
It lends itself to a significantly better drafting experience.