name: "Rust build & test"

on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master', 'develop' ]

env:
  CARGO_TERM_COLOR: always
  SOURCE_PATH: "./src"
  TRUNK_VERSION: "0.16.0"
  TAURI_CLI_VERSION: "1.1.1"

jobs:
  tauri-build:
    strategy:
      matrix:
        template: [
          'tauri-linux-build',
          'tauri-macos-build',
          'tauri-windows-build'
        ]
    uses: './.github/workflows/templates/${{ matrix.template }}.yml'
    with:
      TRUNK_VERSION: ${{ env.TRUNK_VERSION }}
      TAURI_CLI_VERSION: ${{ env.TAURI_CLI_VERSION }}

  validate:
    uses: './.github/workflows/templates/validate.yml'

  wasm-build:
    uses: './.github/workflows/templates/wasm-build.yml'
    with:
      TRUNK_VERSION: ${{ env.TRUNK_VERSION }}

  cli-build:
    uses: './.github/workflows/templates/cli-builds.yml'

  cordova-build:
    uses: './.github/workflows/templates/cordova-build.yml'
    needs: wasm-build
