name: Builds the Cordova project from pre-built WASM

on:
  workflow_call:

jobs:
  cordova-build:
    container:
      image: cimg/android:2022.09.2-node
      options: --user root
    runs-on: ubuntu-latest
    steps:
      - name: Install cordova
        run: npm install -g cordova@11.0.0
      - name: Install Android build tools
        run: sdkmanager "build-tools;32.0.0"
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ env.SOURCE_PATH }}
      - name: Download compiled WASM
        uses: actions/download-artifact@v3
        with:
          name: CubeShuffle-wasm
          path: "${{ env.SOURCE_PATH }}/cube_shuffle-cordova/www"
      - name: Build Android
        working-directory: "${{ env.SOURCE_PATH }}/cube_shuffle-cordova"
        run: |
          cordova platform add android --no-telemetry --verbose
          cordova build android --device --release --no-telemetry --verbose
      - name: Extract build output
        run: mv "${{ env.SOURCE_PATH }}/cube_shuffle-cordova/platforms/android/app/build/outputs/bundle/release/app-release.aab" "./CubeShuffle_Android.aab"
      - uses: actions/upload-artifact@v3
        with:
          name: CubeShuffle-Cordova-Android-Bundle
          if-no-files-found: error
          path: "./CubeShuffle_Android.aab"

  apk-generate:
    container:
      image: openjdk:19-jdk-slim-bullseye
    runs-on: ubuntu-latest
    needs: [ cordova-build ]
    steps:
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install wget unzip git
      - uses: actions/checkout@v3
        with:
          submodules: false
          path: ${{ env.SOURCE_PATH }}
      - name: Download bundletool
        run: wget -O bundletool.jar https://github.com/google/bundletool/releases/download/1.9.0/bundletool-all-1.9.0.jar
      - name: Download AAB
        uses: actions/download-artifact@v3
        with:
          name: CubeShuffle-Cordova-Android-Bundle
      - name: Build signed APKS
        if: startsWith(github.ref, 'refs/tags/v')
        run: >
          java -jar "./bundletool.jar" build-apks
          --mode="universal"
          --ks="${{ env.SOURCE_PATH }}/cubeshuffle.keystore"
          --ks-pass="pass:${{ secrets.KEYSTORE_PASSWORD }}"
          --ks-key-alias="cush"
          --bundle="./CubeShuffle_Android.aab"
          --output="./CubeShuffle_Android.apks"
      - name: Build unsigned APKS
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: >
          java -jar "./bundletool.jar" build-apks
          --mode="universal"
          --bundle="./CubeShuffle_Android.aab"
          --output="./CubeShuffle_Android.apks"
      - name: Extract APK
        run: unzip -p "./CubeShuffle_Android.apks" "universal.apk" > "./CubeShuffle_Android.apk"
      - uses: actions/upload-artifact@v3
        with:
          name: CubeShuffle-Cordova-Android-Universal
          if-no-files-found: error
          path: |
            ./CubeShuffle_Android.apk