name: Publish a new version

on:
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/build.yml'

  publish:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
      - name: List artifacts
        run: ls -R
      - name: Install jq
        run: |
          sudo apt-get -y update
          sudo apt-get -y install jq
      - name: Make update json
        run: |
          jq -n \
          --arg version "${GITHUB_REF##*/v}" \
          --arg tag_version "${GITHUB_REF##*/}" \
          --arg now `date --iso-8601=ns` \
          '{
            "name": $version,
            "notes": "All releases at https://github.com/philipborg/CubeShuffle/releases",
            "pub_date": $now,
            "platforms": {
              "darwin-aarch64": {
                "signature": "",
                "url": ("https://github.com/philipborg/CubeShuffle/releases/download/" + $tag_version + "/CubeShuffle-GUI.app.tar.gz")
              },
              "darwin-x86_64": {
                "signature": "",
                "url": ("https://github.com/philipborg/CubeShuffle/releases/download/" + $tag_version + "/CubeShuffle-GUI.app.tar.gz")
              },
              "linux-x86_64": {
                "signature": "",
                "url": ("https://github.com/philipborg/CubeShuffle/releases/download/" + $tag_version + "/CubeShuffle-GUI.AppImage.tar.gz")
              },
              "windows-x86_64": {
                "signature": "",
                "url": ("https://github.com/philipborg/CubeShuffle/releases/download/" + $tag_version + "/CubeShuffle-GUI.msi.zip")
              }
            }
          }' \
          > "update_info.json"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
          prerelease: true
          files: |
            CubeShuffle-Cordova-Android-Bundle/CubeShuffle_Android.aab
            CubeShuffle-Cordova-Android-Universal/CubeShuffle_Android.apk
            CubeShuffle-Tauri_Linux_X64.AppImage/CubeShuffle-GUI.AppImage
            CubeShuffle-Tauri_Linux_X64.AppImage/CubeShuffle-GUI.AppImage.tar.gz
            CubeShuffle-Tauri_Linux_X64.deb/CubeShuffle-GUI.deb
            CubeShuffle-Tauri_Windows_X64.msi/CubeShuffle-GUI.msi
            CubeShuffle-Tauri_Windows_X64.msi/CubeShuffle-GUI.msi.zip
            CubeShuffle-Tauri_macOS_Universal.dmg/CubeShuffle-GUI.dmg
            CubeShuffle-Tauri_macOS_Universal.app/CubeShuffle-GUI.app.tar.gz
            CubeShuffle-cli_*/*
            update_info.json