name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: ./src
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: clippy
          override: true
      - name: Install webkit/GTK dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            patchelf \
            librsvg2-dev
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Install Tauri
        run: cargo install tauri-cli --locked --version ^1.0.0-beta
      - name: Tauri Build
        run: cargo tauri build
        working-directory: "./src/src-tauri"
      - uses: actions/upload-artifact@v2
        with:
          name: CubeShuffle-Tauri_${{ matrix.platform }}
          path: |
            ./src/target/cube-shuffle
            ./src/target/release/bundle
      - name: Cargo build
        run: cargo build --verbose --locked
        working-directory: ./src
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --workspace --all-targets --manifest-path "./src/Cargo.toml"
      - name: Run tests
        run: cargo test --verbose --locked
        working-directory: ./src
      - name: Trunk build
        run: trunk build --release --dist "$GITHUB_WORKSPACE/wasm_build"
        working-directory: ./src/cube_shuffle-wasm
      - uses: actions/upload-artifact@v2
        with:
          name: CubeShuffle-wasm_${{ matrix.platform }}
          path: ./wasm_build
