name: "Rust build & test"

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'master', 'develop' ]

env:
  CARGO_TERM_COLOR: always
  SOURCE_PATH: "./src"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: ${{ env.SOURCE_PATH }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{ env.SOURCE_PATH }}
      - name: Install webkit/GTK dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            patchelf \
            librsvg2-dev
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Install Tauri
        run: cargo install tauri-cli --locked --version ^1.0.0-beta
      - name: Tauri Build
        run: cargo tauri build
        working-directory: "${{ env.SOURCE_PATH }}/src-tauri"

      - uses: actions/upload-artifact@v2
        name: Tauri Linux executable
        if: runner.os == 'Linux'
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}_EXECUTABLE
          path: "${{ env.SOURCE_PATH }}/target/release/cube-shuffle"
      - uses: actions/upload-artifact@v2
        name: Tauri Linux deb
        if: runner.os == 'Linux'
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}.deb
          path: "${{ env.SOURCE_PATH }}/target/release/bundle/deb/cube-shuffle*.deb"
      - uses: actions/upload-artifact@v2
        name: Tauri Linux AppImage
        if: runner.os == 'Linux'
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}.AppImage
          path: "${{ env.SOURCE_PATH }}/target/release/bundle/appimage/cube-shuffle*.AppImage"

      - uses: actions/upload-artifact@v2
        name: Tauri macOS app
        if: runner.os == 'macOS'
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}.app
          path: "${{ env.SOURCE_PATH }}/target/release/bundle/macos/CubeShuffle*.app"
      - uses: actions/upload-artifact@v2
        name: Tauri macOS dmg
        if: runner.os == 'macOS'
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}.dmg
          path: "${{ env.SOURCE_PATH }}/target/release/bundle/dmg/CubeShuffle*.dmg"

      - name: Cargo build
        run: cargo build --verbose --locked
        working-directory: ${{ env.SOURCE_PATH }}
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --workspace --all-targets --manifest-path "${{ env.SOURCE_PATH }}/Cargo.toml"
      - name: Run tests
        run: cargo test --verbose --locked
        working-directory: ${{ env.SOURCE_PATH }}
      - name: Trunk build
        run: trunk build --release --dist "$GITHUB_WORKSPACE/wasm_build"
        working-directory: "${{ env.SOURCE_PATH }}/cube_shuffle-wasm"
      - uses: actions/upload-artifact@v2
        with:
          name: CubeShuffle-wasm_${{ matrix.platform }}
          path: ./wasm_build
