name: Tauri Linux Build

on:
  workflow_call:
    inputs:
      TRUNK_VERSION:
        required: true
        type: string
      TAURI_VERSION:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  SOURCE_PATH: "./src"

jobs:
  build-tauri:
    name: Builds Tauri for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install webkit/GTK dependencies (Linux)
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ env.SOURCE_PATH }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{ env.SOURCE_PATH }}
          cache-on-failure: true
          key: Trunk_${{ inputs.TRUNK_VERSION }}-TauriCLI_${{ inputs.TAURI_CLI_VERSION }}
      - name: Install Trunk
        run: cargo install --locked trunk --version ${{ inputs.TRUNK_VERSION }}
      - name: Install Tauri
        run: cargo install tauri-cli --locked --version ${{ inputs.TAURI_CLI_VERSION }}

      - name: Tauri Build
        run: cargo tauri build || true
        working-directory: "${{ env.SOURCE_PATH }}/src-tauri"

      - uses: actions/upload-artifact@v3
        name: Tauri Linux executable
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}_EXECUTABLE
          path: "${{ env.SOURCE_PATH }}/target/release/cube-shuffle"
      - name: Exfiltrate deb
        run: mv "${{ env.SOURCE_PATH }}/target/release/bundle/deb/cube-shuffle"*".deb" "CubeShuffle-GUI.deb"
      - uses: actions/upload-artifact@v3
        name: Tauri Linux deb
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}.deb
          path: "CubeShuffle-GUI.deb"
      - name: Exfiltrate AppImage
        run: |
          mv "${{ env.SOURCE_PATH }}/target/release/bundle/appimage/cube-shuffle"*".AppImage" "CubeShuffle-GUI.AppImage"
          mv "${{ env.SOURCE_PATH }}/target/release/bundle/appimage/cube-shuffle"*".AppImage.tar.gz" "CubeShuffle-GUI.AppImage.tar.gz"
      - uses: actions/upload-artifact@v3
        name: Tauri Linux AppImage
        with:
          if-no-files-found: error
          name: CubeShuffle-Tauri_${{ runner.os }}_${{ runner.arch }}.AppImage
          path: "CubeShuffle-GUI.AppImage*"
